# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/Desktop/Code/ui/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tabHosts = QtWidgets.QWidget()
        self.tabHosts.setObjectName("tabHosts")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tabHosts)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableHosts = QtWidgets.QTableView(self.tabHosts)
        self.tableHosts.setObjectName("tableHosts")
        self.verticalLayout_2.addWidget(self.tableHosts)
        self.tabWidget.addTab(self.tabHosts, "")
        self.tabBlocked = QtWidgets.QWidget()
        self.tabBlocked.setObjectName("tabBlocked")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tabBlocked)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableBlocked = QtWidgets.QTableView(self.tabBlocked)
        self.tableBlocked.setObjectName("tableBlocked")
        self.verticalLayout_3.addWidget(self.tableBlocked)
        self.tabWidget.addTab(self.tabBlocked, "")
        self.tabSettings = QtWidgets.QWidget()
        self.tabSettings.setObjectName("tabSettings")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tabSettings)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.checkAStart = QtWidgets.QCheckBox(self.tabSettings)
        self.checkAStart.setObjectName("checkAStart")
        self.verticalLayout_5.addWidget(self.checkAStart)
        self.checkTray = QtWidgets.QCheckBox(self.tabSettings)
        self.checkTray.setObjectName("checkTray")
        self.verticalLayout_5.addWidget(self.checkTray)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.logLines = QtWidgets.QSpinBox(self.tabSettings)
        self.logLines.setObjectName("logLines")
        self.horizontalLayout_2.addWidget(self.logLines)
        self.labelLogLines = QtWidgets.QLabel(self.tabSettings)
        self.labelLogLines.setObjectName("labelLogLines")
        self.horizontalLayout_2.addWidget(self.labelLogLines)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(17, 362, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.saveSettings = QtWidgets.QPushButton(self.tabSettings)
        self.saveSettings.setObjectName("saveSettings")
        self.verticalLayout_5.addWidget(self.saveSettings)
        self.discardSettings = QtWidgets.QPushButton(self.tabSettings)
        self.discardSettings.setObjectName("discardSettings")
        self.verticalLayout_5.addWidget(self.discardSettings)
        self.tabWidget.addTab(self.tabSettings, "")
        self.tabLogs = QtWidgets.QWidget()
        self.tabLogs.setObjectName("tabLogs")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tabLogs)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.textEdit = QtWidgets.QPlainTextEdit(self.tabLogs)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_4.addWidget(self.textEdit)
        self.tabWidget.addTab(self.tabLogs, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Watch-Fire"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabHosts), _translate("MainWindow", "Hosts"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabBlocked), _translate("MainWindow", "Blocked"))
        self.checkAStart.setText(_translate("MainWindow", "Autostart"))
        self.checkTray.setText(_translate("MainWindow", "Minimize to tray"))
        self.labelLogLines.setText(_translate("MainWindow", "Max lines in Log"))
        self.saveSettings.setText(_translate("MainWindow", "Save"))
        self.discardSettings.setText(_translate("MainWindow", "Discard"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSettings), _translate("MainWindow", "Settings"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabLogs), _translate("MainWindow", "Logs"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
